name: vouchervision
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - wheel
  - numpy==1.24.0
  - opencv
  - streamlit
  - streamlit-extras
  - plotly
  - pyyaml
  - Pillow
  - pandas
  - matplotlib
  - matplotlib-inline
  - tqdm
  - google-api-python-client
  - google-cloud-aiplatform
  - google-cloud-storage
  - google-cloud-vision
  - google-generativeai
  - transformers
  - sentence-transformers
  - seaborn
  - dask
  - psutil
  - py-cpuinfo
  - openpyxl
  - langchain
  - langchain-community
  - langchain-core
  - langchain-mistralai
  - langchain-openai
  - langchain-google-genai
  - langchain-experimental
  - langchain-google-vertexai
  - 
  - chromadb
  - gputil
  - geocoder
  - accelerate
  - tiktoken
  - wikipedia
  - InstructorEmbedding
  - Levenshtein
  - fuzzywuzzy
  - pycountry-convert
  - mapboxgl
  - openai

  - pip:
    - -r file:requirements_conda.txt
