name: vouchervision
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - wheel
  - numpy
  - opencv
  - Pillow
  - pandas
  - matplotlib
  - matplotlib-inline
  - openpyxl

  - pip:
    - -r file:requirements_conda.txt
