[theme]
    primaryColor = "#00ff00"
    backgroundColor="#1a1a1a"
    secondaryBackgroundColor="#303030"
    textColor = "cccccc"

[server]
    enableStaticServing = false
    runOnSave = true
    port = 8524
    maxUploadSize = 5000